# Generated by Django 5.2.12 on 2026-04-06 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='codigo_estudiante',
            field=models.CharField(help_text='Código único del estudiante en la institución.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='persona',
            field=models.OneToOneField(help_text='Ficha de la persona que es alumno (una sola por persona).', on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='academica.persona'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Opcional; si se informa y no está vacío, debe ser único.', max_length=32),
        ),
        migrations.AlterField(
            model_name='canton',
            name='nombre',
            field=models.CharField(help_text='Ej. Quito, Cuenca.', max_length=120),
        ),
        migrations.AlterField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(help_text='Provincia a la que pertenece este cantón.', on_delete=django.db.models.deletion.CASCADE, related_name='cantones', to='academica.provincia'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nivel_educativo',
            field=models.ForeignKey(blank=True, help_text='Nivel al que pertenece este grado; puede quedar vacío.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados', to='academica.niveleducativo'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(help_text='Ej. 3.º EGB, Décimo año.', max_length=120),
        ),
        migrations.AlterField(
            model_name='grado',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden dentro del listado de grados.'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='asignatura',
            field=models.ForeignKey(help_text='Asignatura del catálogo que se ofrece en este paralelo.', on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academica.asignatura'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='horas_semanales',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Carga horaria semanal acordada para esta oferta; opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='paralelo',
            field=models.ForeignKey(help_text='Grupo (grado + sección + periodo) donde se dicta.', on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academica.paralelo'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='alumno',
            field=models.ForeignKey(help_text='Estudiante inscrito.', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academica.alumno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('retirada', 'Retirada'), ('transferida', 'Transferida'), ('finalizada', 'Finalizada')], default='activa', help_text='Situación actual de la matrícula (activa, retirada, etc.).', max_length=16),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha',
            field=models.DateField(help_text='Fecha de la matrícula o ingreso a ese paralelo.'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='paralelo',
            field=models.ForeignKey(help_text='Grupo (grado + sección + periodo) en el que queda matriculado.', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academica.paralelo'),
        ),
        migrations.AlterField(
            model_name='niveleducativo',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número para listar niveles en secuencia (menor = antes).'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo_iso',
            field=models.CharField(blank=True, help_text='Código ISO de 3 letras, ej. ECU. Opcional.', max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(help_text='Nombre del país, ej. Ecuador.', max_length=120),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='grado',
            field=models.ForeignKey(help_text='Curso o año de este paralelo.', on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='academica.grado'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='periodo_lectivo',
            field=models.ForeignKey(help_text='Año o ciclo en el que existe este grupo.', on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='academica.periodolectivo'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='seccion',
            field=models.CharField(help_text='Letra o identificador de sección, ej. A, B, 1.', max_length=16),
        ),
        migrations.AlterField(
            model_name='periodolectivo',
            name='es_actual',
            field=models.BooleanField(default=False, help_text='Marcar el periodo que la institución considera activo ahora.'),
        ),
        migrations.AlterField(
            model_name='periodolectivo',
            name='nombre',
            field=models.CharField(help_text='Ej. 2025-2026, Ciclo 1 2025.', max_length=64),
        ),
        migrations.AlterField(
            model_name='persona',
            name='canton',
            field=models.ForeignKey(blank=True, help_text='Cantón de residencia o referencia; opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='academica.canton'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(blank=True, help_text='Cédula u otro documento; único en el sistema si se informa.', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario para iniciar sesión; no toda persona tiene cuenta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personarol',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Si tiene valor, el rol ya no aplica después de esta fecha.', null=True),
        ),
        migrations.AlterField(
            model_name='personarol',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Cuándo comenzó a tener este rol; opcional.', null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codigo_docente',
            field=models.CharField(help_text='Código único del docente en la institución.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='persona',
            field=models.OneToOneField(help_text='Ficha de la persona que es docente (una sola por persona).', on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to='academica.persona'),
        ),
        migrations.AlterField(
            model_name='profesormateria',
            name='materia',
            field=models.ForeignKey(help_text='Oferta concreta (asignatura + paralelo) que imparte el profesor.', on_delete=django.db.models.deletion.CASCADE, related_name='profesor_materias', to='academica.materia'),
        ),
        migrations.AlterField(
            model_name='profesormateria',
            name='profesor',
            field=models.ForeignKey(help_text='Docente asignado.', on_delete=django.db.models.deletion.CASCADE, related_name='profesor_materias', to='academica.profesor'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(help_text='Ej. Pichincha, Guayas.', max_length=120),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='pais',
            field=models.ForeignKey(help_text='País al que pertenece esta provincia.', on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='academica.pais'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='codigo',
            field=models.SlugField(help_text='Identificador corto sin espacios, ej. director, secretario.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(help_text='Nombre legible del rol.', max_length=120),
        ),
    ]
