# Generated by Django 5.2.12 on 2026-04-06 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0002_alter_alumno_codigo_estudiante_alter_alumno_persona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodolectivo',
            name='modo_division_anual',
            field=models.CharField(choices=[('trimestral', 'Trimestral (3 periodos)'), ('quimestral', 'Quimestral (2 periodos)')], default='quimestral', help_text='Cómo se divide el año para calificaciones parciales (libretas por quimestre o trimestre).', max_length=16),
        ),
        migrations.CreateModel(
            name='MateriaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('cursando', 'Cursando'), ('convalidada', 'Convalidada'), ('retirada', 'Retirada de la materia')], default='cursando', max_length=16)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, help_text='Fecha en que se registró la asignación.')),
                ('materia', models.ForeignKey(help_text='Oferta (asignatura en ese paralelo) que cursa.', on_delete=django.db.models.deletion.CASCADE, related_name='materias_asignadas', to='academica.materia')),
                ('matricula', models.ForeignKey(help_text='Matrícula del estudiante en el paralelo.', on_delete=django.db.models.deletion.CASCADE, related_name='materias_asignadas', to='academica.matricula')),
            ],
            options={
                'verbose_name': 'materia asignada',
                'verbose_name_plural': 'materias asignadas',
                'ordering': ['matricula', 'materia'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año del mes de la libreta, ej. 2025.')),
                ('mes', models.PositiveSmallIntegerField(help_text='Mes 1–12.')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional si la UE usa solo observaciones cualitativas.', max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, default='', help_text='Informe o comentario para la libreta mensual.')),
                ('materia_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_mensuales', to='academica.materiaasignada')),
            ],
            options={
                'verbose_name': 'calificación mensual',
                'verbose_name_plural': 'calificaciones mensuales',
                'ordering': ['-anio', '-mes', 'materia_asignada'],
            },
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='planificada', max_length=16)),
                ('tema', models.CharField(blank=True, default='', max_length=200)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('profesor_materia', models.ForeignKey(help_text='Docente y materia ofertada de esta clase.', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_clase', to='academica.profesormateria')),
            ],
            options={
                'verbose_name': 'sesión de clase',
                'verbose_name_plural': 'sesiones de clase',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificado', 'Justificado'), ('atraso', 'Atraso')], default='presente', max_length=16)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('materia_asignada', models.ForeignKey(help_text='Inscripción del estudiante en la materia (debe coincidir con el paralelo de la sesión).', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academica.materiaasignada')),
                ('sesion_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academica.sesionclase')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ['sesion_clase', 'materia_asignada'],
            },
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(help_text='1 = primera unidad del año, 2 = segunda, etc.')),
                ('nombre', models.CharField(help_text='Ej. Primer quimestre, Segundo trimestre.', max_length=64)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('periodo_lectivo', models.ForeignKey(help_text='Año lectivo al que pertenece esta unidad.', on_delete=django.db.models.deletion.CASCADE, related_name='unidades_academicas', to='academica.periodolectivo')),
            ],
            options={
                'verbose_name': 'unidad académica',
                'verbose_name_plural': 'unidades académicas',
                'ordering': ['periodo_lectivo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('materia_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_unidad', to='academica.materiaasignada')),
                ('unidad_academica', models.ForeignKey(help_text='Quimestre o trimestre al que corresponde la nota.', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academica.unidadacademica')),
            ],
            options={
                'verbose_name': 'calificación por unidad',
                'verbose_name_plural': 'calificaciones por unidad',
                'ordering': ['unidad_academica', 'materia_asignada'],
            },
        ),
        migrations.AddConstraint(
            model_name='materiaasignada',
            constraint=models.UniqueConstraint(fields=('matricula', 'materia'), name='uniq_materia_asignada_matricula_materia'),
        ),
        migrations.AddConstraint(
            model_name='calificacionmensual',
            constraint=models.UniqueConstraint(fields=('materia_asignada', 'anio', 'mes'), name='uniq_calif_mensual_materia_anio_mes'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('sesion_clase', 'materia_asignada'), name='uniq_asistencia_sesion_materia_asignada'),
        ),
        migrations.AddConstraint(
            model_name='unidadacademica',
            constraint=models.UniqueConstraint(fields=('periodo_lectivo', 'orden'), name='uniq_unidad_orden_por_periodo'),
        ),
        migrations.AddConstraint(
            model_name='calificacionunidad',
            constraint=models.UniqueConstraint(fields=('materia_asignada', 'unidad_academica'), name='uniq_calif_unidad_materia_unidad'),
        ),
    ]
